---

x-common-environment: &common-env
  ASPNETCORE_ENVIRONMENT: Development

services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  bot:
    environment:
      <<: *common-env
      WordLists__en__SolutionWordsFile: /app/bin/Debug/net9.0/Words/en-solution.txt
      WordLists__en__GuessWordsFile: /app/bin/Debug/net9.0/Words/en-guess.txt
      WordLists__es__SolutionWordsFile: /app/bin/Debug/net9.0/Words/es-solution.txt
    build:
      context: .
      dockerfile: Blink3.Bot/Dockerfile

  scout:
    environment:
      <<: *common-env
    build:
      context: .
      dockerfile: Blink3.Scout/Dockerfile

  api:
    environment:
      <<: *common-env
    build:
      context: .
      dockerfile: Blink3.API/Dockerfile
    ports:
      - "8288:8080"