version: '3.8'

services:
  blink3.bot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - WordLists__en__SolutionWordsFile=/app/bin/Debug/net8.0/Words/en-solution.txt
      - WordLists__en__GuessWordsFile=/app/bin/Debug/net8.0/Words/en-guess.txt
    build:
      context: .
      dockerfile: Blink3.Bot/Dockerfile

  blink3.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Blink3.API/Dockerfile
    ports:
      - "8288:8080"
  
  blink3.web:
    build:
      context: .
      dockerfile: Blink3.Web/Dockerfile
    volumes:
      - ./Blink3.Web/wwwroot/appsettings.json:/usr/share/nginx/html/appsettings.json
    ports:
      - "8280:80"

  blink3.activity:
    build:
      context: .
      dockerfile: Blink3.Activity/Dockerfile
    ports:
      - "8380:80"