# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "/Users/joshua/RiderProjects/Blink3"
      dockerfile: "Blink3.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57439"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ghcr.io/epicofficer/blink3.api:dev"
    ports:
    - "127.0.0.1:57039:57000"
    - "127.0.0.1:57239:57200"
    - "127.0.0.1:57439:57439"
    volumes:
    - "/Users/joshua/RiderProjects/Blink3/Blink3.API:/app:rw"
    - "/Users/joshua/RiderProjects/Blink3:/src:rw"
    - "/Users/joshua/.microsoft/usersecrets:/home/app/.microsoft/usersecrets"
    - "/Users/joshua/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/joshua/.local/share/JetBrains/RiderRemoteDebugger/2025.1.2/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/joshua/Library/Logs/JetBrains/Rider2025.1/DebuggerWorker/JetBrains.Debugger.Worker.2025_6_07_15_33_40:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  bot:
    build:
      context: "/Users/joshua/RiderProjects/Blink3"
      dockerfile: "Blink3.Bot/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57440"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ghcr.io/epicofficer/blink3.bot:dev"
    ports:
    - "127.0.0.1:57040:57000"
    - "127.0.0.1:57240:57200"
    - "127.0.0.1:57440:57440"
    volumes:
    - "/Users/joshua/RiderProjects/Blink3/Blink3.Bot:/app:rw"
    - "/Users/joshua/RiderProjects/Blink3:/src:rw"
    - "/Users/joshua/.microsoft/usersecrets:/home/app/.microsoft/usersecrets"
    - "/Users/joshua/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/joshua/.local/share/JetBrains/RiderRemoteDebugger/2025.1.2/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/joshua/Library/Logs/JetBrains/Rider2025.1/DebuggerWorker/JetBrains.Debugger.Worker.2025_6_07_15_33_40:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  web:
    build:
      context: "/Users/joshua/RiderProjects/Blink3"
      dockerfile: "Blink3.Web/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-musl-arm64/dotnet/dotnet"
    - "exec"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57441"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ghcr.io/epicofficer/blink3.web:dev"
    ports:
    - "127.0.0.1:57041:57000"
    - "127.0.0.1:57241:57200"
    - "127.0.0.1:57441:57441"
    volumes:
    - "/Users/joshua/RiderProjects/Blink3/Blink3.Web:/app:rw"
    - "/Users/joshua/RiderProjects/Blink3:/src:rw"
    - "/Users/joshua/.nuget/packages:/root/.nuget/packages"
    - "/Users/joshua/.local/share/JetBrains/RiderRemoteDebugger/2025.1.2/LinuxMuslArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/joshua/Library/Logs/JetBrains/Rider2025.1/DebuggerWorker/JetBrains.Debugger.Worker.2025_6_07_15_33_40:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
