name: Build & publish Blink Docker images
on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Blink3.API/Dockerfile
            image: ghcr.io/epicofficer/blink3.api
          - dockerfile: ./Blink3.Bot/Dockerfile
            image: ghcr.io/epicofficer/blink3.bot
          - dockerfile: ./Blink3.Web/Dockerfile
            image: ghcr.io/epicofficer/blink3.web
          - dockerfile: ./Blink3.Activity/Dockerfile
            image: ghcr.io/epicofficer/blink3.activity
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=raw,pattern=latest,value=latest
            type=sha,prefix=commit_,

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}