name: Publish Docker Images
on:
  push:
    branches:
      - main
      
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Blink3.API, Blink3.Bot, Blink3.Web]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
     
    - name: Extract SHA
      id: sha
      run: echo "::set-output name=sha::$(echo ${GITHUB_SHA::8})"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.dockerfile }}
        file: ${{ matrix.dockerfile }}/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.actor }}/${{ toLower(matrix.dockerfile) }}:${{ steps.sha.outputs.sha }}
          ghcr.io/${{ github.actor }}/${{ toLower(matrix.dockerfile) }}:latest
