name: Publish Docker images
on:
  release:
    types: [ created ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Blink3.API/Dockerfile
            image: ghcr.io/epicofficer/blink3.api
          - dockerfile: ./Blink3.Bot/Dockerfile
            image: ghcr.io/epicofficer/blink3.bot
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=raw,pattern=latest,value=latest
            type=sha,prefix=commit_,

      - name: Build images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} 
